version: 0.0
os: linux
files:
 - source: .
   destination: /home/ubuntu/share-critic
hooks:
  BeforeInstall:
    - location: scripts/before_install
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
  ApplicationStart:
   - location: scripts/start_server
     timeout: 300